version: '3.9'
   
services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: 
      context: .
      args:
        - DJANGO_ENV=dev
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  rabbitmq:
    image: rabbitmq:3.9.14-management-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      # protol amqp 5671 5672
      # protol http 15671 15672
      - 15672:15672
  worker:
    image: backend-assesment_web
    restart: unless-stopped
    env_file: .env
    command: celery -A core worker -l info
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./backend:/code
  beat:
    image: backend-assesment_web
    restart: unless-stopped
    env_file: .env
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - db
      - rabbitmq
      - worker
    volumes:
      - ./backend:/code